apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-tasks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: get-tasks
  template:
    metadata:
      labels:
        app: get-tasks
    spec:
      containers:
      - name: get-tasks                                         
        image: shivesh183/get-task
        ports:
        - containerPort: 8000
        env:
          - name: FRUITNAME
            valueFrom:
              configMapKeyRef:
                key: FRUITNAME3
                name: fruitdetails        
          - name: CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                  key: kchbhi
                  name: dbdetails	         
